# Generated by Django 4.1.1 on 2022-12-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_adduser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
